fixed spelling

diff --git a/vpn b/vpn
--- a/vpn
+++ b/vpn
@@ -11,11 +11,11 @@ vpntype="wireguard"
 # run 'nmcli con import type wireguard file /etc/wireguard/wg0.conf' to use nmcli connection
 
 if nmcli connection show --active | grep "$vpnint" > /dev/null ; then
-  printf "Wireguard is currently running\nWould you like to disconnect from Wireguard '%s' [y/n]?: " "$vpnint" >&2
+  printf "WireGuard is currently running\nWould you like to disconnect from WireGuard '%s' [y/n]?: " "$vpnint" >&2
   read -r varClose
   case $varClose in
     y|Y )
-      echo "Bringing Wireguard tunnel '$vpnint' down"
+      echo "Bringing WireGuard tunnel '$vpnint' down"
       wg-quick down "$vpnint"
       #nmcli connection down $vpnint
       # Will reconnect current network to fix 'resolv.conf'
@@ -23,26 +23,27 @@ if nmcli connection show --active | grep "$vpnint" > /dev/null ; then
       #nmcli connection up "$con"
       ;;
     n|N )
-      echo "Leaving Wireguard '$vpnint' connected"
+      echo "Leaving WireGuard '$vpnint' connected"
       ;;
     * )
-      printf "\nInvalid entry\nLeaving Wireguard '%s' connected\nRerun command if you'd like to change options" "$vpnint"
+      printf "\nInvalid entry\nLeaving WireGuard '%s' connected\nRerun command if you'd like to change options" "$vpnint"
       ;;
   esac
 else
-  printf "Wireguard tunnel '%s' is not connected\nWould you like to connect '%s' tunnel [y/n]?: " "$vpnint" "$vpnint" >&2
+  printf "WireGuard tunnel '%s' is not connected\nWould you like to connect '%s' tunnel [y/n]?: " "$vpnint" "$vpnint" >&2
   read -r varConnect
   case $varConnect in
     y|Y )
-      echo "Connecting to wireguard tunnel '$vpnint'"
+      echo "Connecting to WireGuard tunnel '$vpnint'"
       #nmcli connection up $vpnint
       wg-quick up "$vpnint"
       ;;
     n|N )
-      echo "Leaving wireguard tunnel '$vpnint' down"
+      echo "Leaving WireGuard tunnel '$vpnint' down"
       ;;
     * )
-      printf "\nInvalid entry\nLeaving wireguard tunnel '%s' down\nRerun command if you'd like to change options" "$vpnint"
+      printf "\nInvalid entry\nLeaving WireGuard tunnel '%s' down\nRerun command if you'd like to change options" "$vpnint"
       ;;
   esac
 fi
+
