fixed errors/removed unused variables

diff --git a/vpn b/vpn
--- a/vpn
+++ b/vpn
@@ -5,45 +5,44 @@
 #Change to name of network interface 'nmcli connection show -a' to list interfaces connected
 vpnint="wg0"
 vpntype="wireguard"
-vpn=$(nmcli -t connection show | grep "$vpntype" | awk -F: '{ print $1 }')
 
 # Need wireguard-tools & NetworkManager installed.
 # Put .conf file in /etc/wireguard/wg0.conf to use wg-quick
 # run 'nmcli con import type wireguard file /etc/wireguard/wg0.conf' to use nmcli connection
 
-if nmcli connection show --active | grep "$vpnint"; then
-  printf "Wireguard is currently running\nWould you like disconnect Wireguard '%s' [y/n]?: " "$vpn" >&2
+if nmcli connection show --active | grep "$vpnint" > /dev/null ; then
+  printf "Wireguard is currently running\nWould you like to disconnect from Wireguard '%s' [y/n]?: " "$vpnint" >&2
   read -r varClose
   case $varClose in
     y|Y )
-      echo "Bringing Wireguard tunnel '$vpn' down"
+      echo "Bringing Wireguard tunnel '$vpnint' down"
       wg-quick down "$vpnint"
-      #nmcli connection down $vpn
+      #nmcli connection down $vpnint
       # Will reconnect current network to fix 'resolv.conf'
       #con=$(nmcli connection show -a | awk -F '  ' 'FNR == 2 {print $1}')
       #nmcli connection up "$con"
       ;;
     n|N )
-      echo "Leaving Wireguard '$vpn' connected"
+      echo "Leaving Wireguard '$vpnint' connected"
       ;;
     * )
-      printf "\nInvalid entry\nLeaving Wireguard '%s' connected\nRerun command if you'd like to change options" "$vpn"
+      printf "\nInvalid entry\nLeaving Wireguard '%s' connected\nRerun command if you'd like to change options" "$vpnint"
       ;;
   esac
 else
-  printf "Wireguard tunnel '%s' is not connected\nWould you like to connect '%s' tunnel [y/n]?: " "$vpn" "$vpn" >&2
+  printf "Wireguard tunnel '%s' is not connected\nWould you like to connect '%s' tunnel [y/n]?: " "$vpnint" "$vpnint" >&2
   read -r varConnect
   case $varConnect in
     y|Y )
-      echo "Connecting to wireguard tunnel '$vpn'"
-      #nmcli connection up $vpn
+      echo "Connecting to wireguard tunnel '$vpnint'"
+      #nmcli connection up $vpnint
       wg-quick up "$vpnint"
       ;;
     n|N )
-      echo "Leaving wireguard tunnel '$vpn' down"
+      echo "Leaving wireguard tunnel '$vpnint' down"
       ;;
     * )
-      printf "\nInvalid entry\nLeaving wireguard tunnel '%s' down\nRerun command if you'd like to change options" "$vpn"
+      printf "\nInvalid entry\nLeaving wireguard tunnel '%s' down\nRerun command if you'd like to change options" "$vpnint"
       ;;
   esac
 fi
